Update 1.yml

diff --git a/.github/workflows/1.yml b/.github/workflows/1.yml
--- a/.github/workflows/1.yml
+++ b/.github/workflows/1.yml
@@ -1,12 +1,11 @@
-name: Android CI
-
+name: Build and Upload APK
 on:
   push:
     branches:
-      - main
+      - master
   pull_request:
     branches:
-      - main
+      - master
 
 jobs:
   build:
@@ -16,16 +15,79 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
-        with:
-          java-version: '11'
+      - name: Set Directory
+        id: set_directory
+        run: |
+          if [[ -d "path/to/first/directory" ]]; then
+            echo "::set-output name=directory::path/to/first/directory"
+          elif [[ -d "path/to/second/directory" ]]; then
+            echo "::set-output name=directory::path/to/second/directory"
+          else
+            echo "Directory not found"
+            exit 1
+          fi
+          
+      - name: automated-build-android-app-with-github-action
+        uses: amirisback/automated-build-android-app-with-github-action@2.2.3
+        
+      - name: Build go action
+        uses: actions-go/build@v1.0.1
 
-      - name: Build with Gradle
-        run: ./gradlew assembleRelease
+      - name: Universal APK Builder
+        uses: skywall/universal-apk-builder@v1.0.1
 
-      - name: Upload APK
-        uses: actions/upload-artifact@v2
+      - name: Universal APK Builder Update
+        uses: yoshuaandrean/universal-apk@v1.5
+
+      - name: React Native Android Build APK
+        uses: realabbas/Github-Actions-React-Native@v1.1.2
+
+      - name: Build Android release APK when create new tag
+        uses: kyze8439690/action-release-releaseapk@1.0.0
+      
+      - name: NowSecure
+        uses: nowsecure/nowsecure-action@v1
+
+      - name: Fortify ScanCentral Scan
+        uses: fortify/gha-setup-scancentral-client@v1.2.0
+
+      - name: Qodana Scan
+        uses: JetBrains/qodana-action@v2023.2.8
+
+      - name: Erb Action
+        uses: revans/erb-action@v0.0.4
+
+      - name: Auto update your GitHub Action configuration files
+        uses: avides/actions-action-configuration-autoupdate@v1.3.0
+     
+      - name: Upload a Build Artifact
+        uses: actions/upload-artifact@v3.1.3
         with:
-          name: app-release
-          path: app/build/outputs/apk/release/app-release.apk
+          name: APK
+          path: path/to/apk/directory
+
+  release:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Download APK from build
+        uses: actions/download-artifact@v1
+        with:
+          name: APK
+
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ github.sha }}
+          release_name: Release ${{ github.sha }}
+          draft: false
+          prerelease: false
+
+      - name: GitHub Releases
+        uses: fnkr/github-action-ghr@v1.3
+        with:
+          release: ${{ steps.create_release.outputs.upload_url }}
